// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: links.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalLink string `protobuf:"bytes,1,opt,name=originalLink,proto3" json:"originalLink,omitempty"`
}

func (x *ShortLinkRequest) Reset() {
	*x = ShortLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLinkRequest) ProtoMessage() {}

func (x *ShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_links_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLinkRequest.ProtoReflect.Descriptor instead.
func (*ShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_links_proto_rawDescGZIP(), []int{0}
}

func (x *ShortLinkRequest) GetOriginalLink() string {
	if x != nil {
		return x.OriginalLink
	}
	return ""
}

type ShortLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortLink string `protobuf:"bytes,1,opt,name=shortLink,proto3" json:"shortLink,omitempty"`
}

func (x *ShortLinkResponse) Reset() {
	*x = ShortLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLinkResponse) ProtoMessage() {}

func (x *ShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_links_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLinkResponse.ProtoReflect.Descriptor instead.
func (*ShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_links_proto_rawDescGZIP(), []int{1}
}

func (x *ShortLinkResponse) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

type GetOriginalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortLink string `protobuf:"bytes,1,opt,name=shortLink,proto3" json:"shortLink,omitempty"`
}

func (x *GetOriginalRequest) Reset() {
	*x = GetOriginalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOriginalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalRequest) ProtoMessage() {}

func (x *GetOriginalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_links_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalRequest) Descriptor() ([]byte, []int) {
	return file_links_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalRequest) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

type GetOriginalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalLink string `protobuf:"bytes,1,opt,name=originalLink,proto3" json:"originalLink,omitempty"`
}

func (x *GetOriginalResponse) Reset() {
	*x = GetOriginalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_links_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOriginalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalResponse) ProtoMessage() {}

func (x *GetOriginalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_links_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalResponse) Descriptor() ([]byte, []int) {
	return file_links_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalResponse) GetOriginalLink() string {
	if x != nil {
		return x.OriginalLink
	}
	return ""
}

var File_links_proto protoreflect.FileDescriptor

var file_links_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x69, 0x6e, 0x6b, 0x73, 0x22, 0x36, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x31, 0x0a, 0x11,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x22,
	0x32, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69,
	0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x22, 0x39, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x32, 0x95,
	0x01, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x40, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x17, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x19, 0x2e,
	0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_links_proto_rawDescOnce sync.Once
	file_links_proto_rawDescData = file_links_proto_rawDesc
)

func file_links_proto_rawDescGZIP() []byte {
	file_links_proto_rawDescOnce.Do(func() {
		file_links_proto_rawDescData = protoimpl.X.CompressGZIP(file_links_proto_rawDescData)
	})
	return file_links_proto_rawDescData
}

var file_links_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_links_proto_goTypes = []interface{}{
	(*ShortLinkRequest)(nil),    // 0: links.ShortLinkRequest
	(*ShortLinkResponse)(nil),   // 1: links.ShortLinkResponse
	(*GetOriginalRequest)(nil),  // 2: links.GetOriginalRequest
	(*GetOriginalResponse)(nil), // 3: links.GetOriginalResponse
}
var file_links_proto_depIdxs = []int32{
	0, // 0: links.Links.OriginalLink:input_type -> links.ShortLinkRequest
	2, // 1: links.Links.GetOriginalLink:input_type -> links.GetOriginalRequest
	1, // 2: links.Links.OriginalLink:output_type -> links.ShortLinkResponse
	3, // 3: links.Links.GetOriginalLink:output_type -> links.GetOriginalResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_links_proto_init() }
func file_links_proto_init() {
	if File_links_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_links_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_links_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_links_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOriginalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_links_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOriginalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_links_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_links_proto_goTypes,
		DependencyIndexes: file_links_proto_depIdxs,
		MessageInfos:      file_links_proto_msgTypes,
	}.Build()
	File_links_proto = out.File
	file_links_proto_rawDesc = nil
	file_links_proto_goTypes = nil
	file_links_proto_depIdxs = nil
}
